// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT1WYuuK-22rgqNLGDVEVX59Yg_NVLEbc',
    appId: '1:681296444869:web:bad15921559d95bce8dfac',
    messagingSenderId: '681296444869',
    projectId: 'prompt-manager-65273',
    authDomain: 'prompt-manager-65273.firebaseapp.com',
    databaseURL: 'https://prompt-manager-65273-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prompt-manager-65273.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlF7q8nHe0VCYjs6LALcKtSTb9DWHup84',
    appId: '1:681296444869:android:31c2a54b2fa22835e8dfac',
    messagingSenderId: '681296444869',
    projectId: 'prompt-manager-65273',
    databaseURL: 'https://prompt-manager-65273-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prompt-manager-65273.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd37cS0XT5Bxw0Slp8dGjec0GIJ3XvNto',
    appId: '1:681296444869:ios:5e554d72dd0720dae8dfac',
    messagingSenderId: '681296444869',
    projectId: 'prompt-manager-65273',
    databaseURL: 'https://prompt-manager-65273-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prompt-manager-65273.firebasestorage.app',
    iosBundleId: 'com.onurerdil.promptManager',
  );

}